[package]
name = "miniscript-qtum"
version = "10.0.0-qtum"
authors = [
	"Andrew Poelstra <apoelstra@wpsoftware.net>", 
	"Sanket Kanjalkar <sanket1729@gmail.com>",
	"The Qtum developers"
	]
license = "CC0-1.0"
homepage = "https://github.com/rust-bitcoin/rust-miniscript/"
repository = "https://github.com/qtumproject/rust-miniscript/"
description = "Miniscript: a subset of Bitcoin Script designed for analysis"
keywords = [ "crypto", "bitcoin", "miniscript", "script" ]
readme = "README.md"
edition = "2018"
autotests = false

[features]
default = ["std"]
std = ["qtum/std", "qtum/secp-recovery"]
no-std = ["hashbrown", "qtum/no-std"]
compiler = []
trace = []

unstable = []
serde = ["actual-serde", "qtum/serde"]
rand = ["qtum/rand"]
base64 = ["qtum/base64"]

[dependencies]
qtum = { path = "../rust-qtum/qtum", version = "0.30.0-qtum", default-features = false }
hashbrown = { version = "0.11", optional = true }
internals = { package = "qtum-private", path = "../rust-qtum/internals" , version = "0.1.0-qtum", default_features = false }

# Do NOT use this as a feature! Use the `serde` feature instead.
actual-serde = { package = "serde", version = "1.0.103", optional = true }

[dev-dependencies]
serde_test = "1.0.147"
qtum = { path = "../rust-qtum/qtum", version = "0.30.0-qtum", features = ["base64"]}
secp256k1 = {version = "0.27.0", features = ["rand-std"]}
actual-base64 = { package = "base64", version = "0.13.0" }

[[example]]
name = "htlc"
required-features = ["std", "compiler"]

[[example]]
name = "parse"
required-features = ["std"]

[[example]]
name = "sign_multisig"
required-features = ["std"]

[[example]]
name = "verify_tx"
required-features = ["std"]

[[example]]
name = "psbt"
required-features = ["std"]

[[example]]
name = "xpub_descriptors"
required-features = ["std"]

[[example]]
name = "taproot"
required-features = ["compiler","std"]

[[example]]
name = "psbt_sign_finalize"
required-features = ["std", "base64"]

[workspace]
members = ["bitcoind-tests", "fuzz"]
exclude = ["embedded"]
